### ISSUE TITLE
ActorCriticPolicy does not expect 'aux_lr_schedule'

### ISSUE THREAD

**Issue by RajS999** [janEbert/sb3-ppg#1]
Have you tried to run this with stable-baselines3?
I quickly tried by dropping your code in stable-baselines3 on my local machine. 
On line ppg.py [line 203](https://github.com/janEbert/sb3-ppg/blob/525d7ef2af485e37809c80cc065072169ebf4014/ppg/ppg.py#L203), you do:

```
self.policy_kwargs["aux_lr_schedule"] = self.aux_lr_schedule
```

Then these calls happen:

- [`[PPO.] super(PPG, self)._setup_model()`](https://github.com/janEbert/sb3-ppg/blob/525d7ef2af485e37809c80cc065072169ebf4014/ppg/ppg.py#L205) 
- [`[OnPolicyAlgorithm.]super(PPO, self)._setup_model()`](https://github.com/DLR-RM/stable-baselines3/blob/c0966f3745e886825cc7a7301b50f466b169cf11/stable_baselines3/ppo/ppo.py#L149)
- And inside this [method](https://github.com/DLR-RM/stable-baselines3/blob/c0966f3745e886825cc7a7301b50f466b169cf11/stable_baselines3/common/on_policy_algorithm.py#L117), there is a call:
   ```
   elf.policy = self.policy_class(  # pytype:disable=not-instantiable
            self.observation_space,
            self.action_space,
            self.lr_schedule,
            use_sde=self.use_sde,
            **self.policy_kwargs  # pytype:disable=not-instantiable
        )
   ``` 
   `policy_class` is `stable_baselines3.common.policies.ActorCriticPolicy` which does not expect parameter `aux_lr_schedule` which you set in `PPG` as `self.policy_kwargs["aux_lr_schedule"]`. So I was getting following error:

```
~/.local/share/virtualenvs/sb3_ppg-k9lk_f-U/lib/python3.8/site-packages/stable_baselines3/ppg/ppg.py in __init__(self, policy, env, learning_rate, aux_learning_rate, n_steps, batch_size, aux_batch_size, n_phases, n_epochs, n_aux_epochs, gamma, gae_lambda, clip_range, clip_range_vf, ent_coef, vf_coef, beta_clone, vf_true_coef, max_grad_norm, use_sde, sde_sample_freq, target_kl, tensorboard_log, create_eval_env, policy_kwargs, use_paper_parameters, verbose, seed, device, _init_setup_model)
    172 
    173         if _init_setup_model:
--> 174             self._setup_model()
    175 
    176     def _set_paper_parameters(self):

~/.local/share/virtualenvs/sb3_ppg-k9lk_f-U/lib/python3.8/site-packages/stable_baselines3/ppg/ppg.py in _setup_model(self)
    203         self.policy_kwargs["aux_lr_schedule"] = self.aux_lr_schedule
    204 
--> 205         super(PPG, self)._setup_model()
    206 
    207     def _update_learning_rate(

~/.local/share/virtualenvs/sb3_ppg-k9lk_f-U/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py in _setup_model(self)
    147 
    148     def _setup_model(self) -> None:
--> 149         super(PPO, self)._setup_model()
    150 
    151         # Initialize schedules for policy/value clipping

~/.local/share/virtualenvs/sb3_ppg-k9lk_f-U/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py in _setup_model(self)
    115             n_envs=self.n_envs,
    116         )
--> 117         self.policy = self.policy_class(  # pytype:disable=not-instantiable
    118             self.observation_space,
    119             self.action_space,

TypeError: __init__() got an unexpected keyword argument 'aux_lr_schedule'
```
Should PPG do `self.policy_kwargs["aux_lr_schedule"] = self.aux_lr_schedule` after calling `super(PPG, self)._setup_model()`? Tried that and it worked but guessing if its correct...
More importantly, have you tried to run this code with sb3? Did you get the same error? Or I am missing something / did something wrong?

**Comment by janEbert** [comment]
Hey, thanks for asking! The reason this happens is if you either
1. only drop the `ppg.py` file in your sb3 repo, or
2. initialize the model with the policy's **class** as the first argument.

If it's 1., just drop the whole `ppg` directory from this repo's root in the sb3 repository's `stable_baselines3` directory. (It seems you did not do this from the logs but just in case someone else stumbles upon this.)

For 2., the reason you get an error is because PPG expects a different policy. I think the recommendation with sb3 is to use a string to initialize the model's policy parameter which is because sb3 keeps a policy registry which automatically picks the right policy class for the corresponding model based on the string given.
So, to fix, either hardcode the `AuxActorCriticPolicy` from `ppg/policies.py`, or use the string `'MLPPolicy'` when initializing the model.

I'll add an error message and usage instructions to prevent this issue. Thanks for reporting!

**Comment by RajS999** [comment]
Sorry, I was a bit lazy and did not explain all things I tried and simply said "dropping your code in stable-baselines3 on my local machine". But I already made some changes to get rid of earlier errors. Now I have also committed my for of stable-baselines3 with your ppg. I have also created two colab notebooks explaining before and after of fixing above error, because I feel I did indeed followed what you suggested and still ended up in error. So, links inline. 

Here is the list of changes I have done:

- Copied all files from your repo's [this folder](https://github.com/janEbert/sb3-ppg/tree/main/ppg) to `stable-baselines3\ppg` [directory](https://github.com/RajS999/stable-baselines3/tree/setup_model_aux_lr_schedule_err/stable_baselines3/ppg) (`setup_model_aux_lr_schedule_err` branch of my forked `stable-baselines3`).
- I got error saying `Unable to import CnnPolicy` on [`ppg.__init__()` line 1](https://github.com/janEbert/sb3-ppg/blob/525d7ef2af485e37809c80cc065072169ebf4014/ppg/__init__.py#L1). You have specified that this policy is missing in readme. So I removed it from the fork's [`ppg.__init__()` line1](https://github.com/RajS999/stable-baselines3/blob/b82d2689dcf2c81724d62ca76e814e31d47248ed/stable_baselines3/ppg/__init__.py#L1). 
- Then I was not able to do `from stable_baselines3 import PPG` and have to do `from stable_baselines3.ppg import PPG`. So added import in [`stable_baselines3.__init__` line10](https://github.com/RajS999/stable-baselines3/blob/b82d2689dcf2c81724d62ca76e814e31d47248ed/stable_baselines3/__init__.py#L10).

With these changes I was getting error specified in original post as you can see in [this notebook cell](https://colab.research.google.com/drive/1vXCT2C0o3RFhIRJRhLUg9ERyF-Z_APZO?authuser=1#scrollTo=0bcTHhk86Ng1&line=1&uniqifier=1). Note that I have installed stable-baselines3 from [above branch](https://github.com/RajS999/stable-baselines3/tree/setup_model_aux_lr_schedule_err/) in this notebook.

So, I made `super()` call before setting parameter in [`PPG._setup_model()`](https://github.com/RajS999/stable-baselines3/blob/ac54f5c30c6671b5ea6eb4fc7a5a74b83479b260/stable_baselines3/ppg/ppg.py#L201)(compare this with [code in earlier notebook](https://colab.research.google.com/drive/1vXCT2C0o3RFhIRJRhLUg9ERyF-Z_APZO?authuser=1#scrollTo=WPeVZMOeEPUb&line=5&uniqifier=1)) :

```    
def _setup_model(self) -> None:
    super(PPG, self)._setup_model()
    self.aux_lr_schedule = get_schedule_fn(self.aux_learning_rate)
    self.policy_kwargs["aux_lr_schedule"] = self.aux_lr_schedule
```

This eliminated earlier error (occurring on instantiating `model=PPG(..)`) as can be seen in [this 2nd notebook cell](https://colab.research.google.com/drive/1QyYK-RghZQ6NslNU68LujMTKXmOGABzb?authuser=1#scrollTo=36Q1vIoaUjZV&line=1&uniqifier=1). (Note that I have installed stable-baselines3 from [2nd branch `setup_model_aux_lr_schedule_err_fixed`](https://github.com/RajS999/stable-baselines3/blob/setup_model_aux_lr_schedule_err_fixed) in my fork in this notebook). However, now ended up getting new error in [this notebook cell](https://colab.research.google.com/drive/1QyYK-RghZQ6NslNU68LujMTKXmOGABzb?authuser=1#scrollTo=i18MzLBrXoDw&line=1&uniqifier=1) (occurring on calling `model.learn(..)`):

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-7dd4ba92d247> in <module>()
----> 1 model.learn(total_timesteps=int(10000))

6 frames
/usr/local/lib/python3.7/dist-packages/stable_baselines3/ppg/ppg.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    329             tb_log_name=tb_log_name,
    330             eval_log_path=eval_log_path,
--> 331             reset_num_timesteps=reset_num_timesteps,
    332         )

/usr/local/lib/python3.7/dist-packages/stable_baselines3/ppo/ppo.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    287             tb_log_name=tb_log_name,
    288             eval_log_path=eval_log_path,
--> 289             reset_num_timesteps=reset_num_timesteps,
    290         )

<<<<<below stack trace is same in my local machine, above stack trace differs and is given at the end>>>>>

/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/on_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    245                 logger.dump(step=self.num_timesteps)
    246 
--> 247             self.train()
    248 
    249         callback.on_training_end()

/usr/local/lib/python3.7/dist-packages/stable_baselines3/ppg/ppg.py in train(self)
    226         """
    227         for phase in range(self.n_phases):
--> 228             super(PPG, self).train()
    229 
    230             indices = np.arange(self.rollout_buffer.buffer_size

/usr/local/lib/python3.7/dist-packages/stable_baselines3/ppo/ppo.py in train(self)
    162         """
    163         # Update optimizer learning rate
--> 164         self._update_learning_rate(self.policy.optimizer)
    165         # Compute current clip range
    166         clip_range = self.clip_range(self._current_progress_remaining)

/usr/local/lib/python3.7/dist-packages/stable_baselines3/ppg/ppg.py in _update_learning_rate(self, optimizers)
    213                       self.aux_lr_schedule(self._current_progress_remaining))
    214         update_learning_rate(
--> 215             self.policy.aux_optimizer,
    216             self.aux_lr_schedule(self._current_progress_remaining))
    217 

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    946                 return modules[name]
    947         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 948             type(self).__name__, name))
    949 
    950     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'ActorCriticPolicy' object has no attribute 'aux_optimizer'
```
On my local machine, I got same error but first two stack frames differ while last five stack trace frames are same. (Find `<<<<< ... >>>>>` in above trace). The initial frames which differ on my local machine are as follows:

```
~/.local/share/virtualenvs/sb3_ppg-k9lk_f-U/lib/python3.8/site-packages/stable_baselines3/ppg/ppg.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    321     ) -> "PPG":
    322 
--> 323         return super(PPG, self).learn(
    324             total_timesteps=total_timesteps,
    325             callback=callback,

~/.local/share/virtualenvs/sb3_ppg-k9lk_f-U/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
    278     ) -> "PPO":
    279 
--> 280         return super(PPO, self).learn(
    281             total_timesteps=total_timesteps,
    282             callback=callback,
```

**Comment by janEbert** [comment]
I don't think you were lazy at all, thanks for the detailed description! So I fixed the wrong import of the CnnPolicy which was an artifact I forgot to remove; thanks for that already! If the code does not work, the reason is still that the policy does not get registered correctly.

If you want the package "integrated" into stable-baselines3 then it's not so simple as you noticed. The changes to `stable_baselines3/__init__.py` were already the first step. Then, I'd suggest you change `ppg/__init__.py` to use absolute imports instead of the relative ones (so you get the following):
```python
from stable_baselines3.ppg.policies import CnnPolicy, MlpPolicy
from stable_baselines3.ppg.ppg import PPG
```

This is the way it's done in PPO as well and that's the only difference I could find between the two algorithms (fingers crossed that it works).

When you move the `_setup_model` call, that means the `aux_lr_schedule` will remain at its default (`None`) and initialization is incomplete (I should also throw an error here).

If it's possible for you, I'd suggest you wait a bit. I was planning to contribute this to [sb3-contrib](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) so it's more accessible to everybody.
